# Telegram 新聞推播系統 - Cloudflare Workers 配置
# 繁體中文註解：此檔案為 Cloudflare Workers 專案的主要配置檔

name = "telegram-news"
main = "src/index.ts"
compatibility_date = "2025-08-14"
compatibility_flags = ["nodejs_compat"]

# Cron 觸發器：每小時整點執行推播任務
[triggers]
crons = ["0 * * * *"]

# D1 資料庫綁定 - 用於存儲新聞貼文和訂閱資料
[[d1_databases]]
binding = "DB"
database_name = "telegram_news_db"
database_id = "placeholder-database-id"  # 將在下一步驟中更新
migrations_dir = "migrations"

# 環境變數配置
[vars]
# 注意：敏感資料（如 Token）將透過 wrangler secret put 設定
# TELEGRAM_BOT_TOKEN - 透過 wrangler secret put 設定
# API_KEY - 透過 wrangler secret put 設定  
# TELEGRAM_WEBHOOK_SECRET - 透過 wrangler secret put 設定

# 開發環境配置
[env.development]
name = "telegram-news-dev"

# 生產環境配置  
[env.production]
name = "telegram-news-prod"
